# Generated by Django 3.1.4 on 2020-12-05 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=100)),
                ('refresh_token', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=21)),
                ('active', models.BooleanField(default=True)),
                ('default_ban_message', models.TextField(blank=True, default='')),
                ('access_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                  to='reddit.authorizeduser')),
            ],
        ),
        migrations.CreateModel(
            name='RemovedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removal_date', models.DateTimeField(auto_created=True, null=True)),
                ('author', models.CharField(default='', max_length=20)),
                ('submission_id', models.CharField(default='', max_length=20, unique=True)),
                ('flair_text_set', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('removal_comment_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('post_title', models.CharField(default='', max_length=1024)),
                ('post_url', models.CharField(blank=True, default='', max_length=1024)),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.subreddit')),
            ],
        ),
        migrations.CreateModel(
            name='RemovalAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flair_text', models.CharField(db_index=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('comment_reply', models.TextField(blank=True, default='')),
                ('ban_duration', models.IntegerField(default=0)),
                ('ban_reason', models.CharField(blank=True, default='', max_length=100)),
                ('use_default_ban_message', models.BooleanField(default=True)),
                ('ban_message', models.TextField(blank=True, default='')),
                ('ban_note', models.CharField(blank=True, default='{0.shortlink}', max_length=200)),
                ('lock_post', models.BooleanField(default=False)),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.subreddit')),
            ],
        ),
    ]
