# Generated by Django 3.1.4 on 2020-12-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='removalaction',
            name='prefix_ban_message_footer',
            field=models.BooleanField(default=True, help_text="Prefix the subreddit's general purpose footer"),
        ),
        migrations.AddField(
            model_name='removalaction',
            name='prefix_ban_message_header',
            field=models.BooleanField(default=True, help_text="Prefix the subreddit's general purpose header"),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='ban_message_footer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='ban_message_header',
            field=models.TextField(blank=True, default=''),
        ),
    ]
