# Generated by Django 3.1.4 on 2020-12-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_auto_20201205_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='removalaction',
            name='prefix_ban_message_footer',
        ),
        migrations.RemoveField(
            model_name='removalaction',
            name='prefix_ban_message_header',
        ),
        migrations.AddField(
            model_name='removalaction',
            name='comment_reply_footer',
            field=models.BooleanField(default=True, help_text="Prefix the subreddit's general purpose reply footer"),
        ),
        migrations.AddField(
            model_name='removalaction',
            name='comment_reply_header',
            field=models.BooleanField(default=True, help_text="Prefix the subreddit's general purpose reply header"),
        ),
    ]
