# Generated by Django 3.1.4 on 2020-12-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_auto_20201205_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='removalaction',
            old_name='comment_reply_header',
            new_name='use_comment_reply_prefix',
        ),
        migrations.RenameField(
            model_name='removalaction',
            old_name='comment_reply_footer',
            new_name='use_comment_reply_suffix',
        ),
        migrations.RenameField(
            model_name='subreddit',
            old_name='ban_message_footer',
            new_name='comment_reply_prefix',
        ),
        migrations.RenameField(
            model_name='subreddit',
            old_name='ban_message_header',
            new_name='comment_reply_suffix',
        ),
    ]
