# Generated by Django 3.1.4 on 2020-12-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0004_auto_20201205_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='removalaction',
            name='permanent_ban',
            field=models.BooleanField(default=False),
        ),
    ]
