# Generated by Django 3.1.4 on 2020-12-05 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0007_removedpost_flair_text_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=21),
        ),
        migrations.AlterField(
            model_name='removedpost',
            name='removal_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reddit.removalaction', verbose_name='Removal Reason'),
        ),
    ]
