# Generated by Django 3.1.4 on 2020-12-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0009_removedpost_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
