# Generated by Django 3.1.4 on 2021-01-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0010_subreddit_read_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='default_ban_message_subject',
            field=models.TextField(blank=True, default=''),
        ),
    ]
